# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='morceau',
            name='artiste_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musiques.Artiste'),
        ),
    ]
