# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0004_auto_20171005_0916'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='morceau',
                name='artiste',
            ),
        migrations.RenameField('morceau', 'artiste_fk', 'artiste'),
    ]
