# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0005_auto_20171010_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morceau',
            name='artiste_fk',
        ),
        migrations.AddField(
            model_name='morceau',
            name='artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to='musiques.Artiste'),
        ),
    ]
