# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0006_auto_20171010_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morceau',
            old_name='artiste',
            new_name='artiste_fk',
        ),
    ]
